ln ./Arcade_gamelist.xml ~/roms/mame/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/fbneo/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/arcade/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/atomiswave/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/aw_dcported/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/naomi/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/cps1/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/cps2/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/cps3/gamelist.xml
ln ./Arcade_gamelist.xml ~/roms/neogeo/gamelist.xml